name: Strapi CI to Heroku

on:
  push:
    branches: [ main ]
    paths:
      - backend/**
  pull_request:
    branches: [ main ]
    paths:
      - backend/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Heroku Action
      uses: CDNievas/heroku-action@v1.0
      with:
        # Used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: "${{ secrets.HEROKU_API_KEY }}"
        heroku_email: "${{ secrets.HEROKU_EMAIL }}"
        heroku_app_name: "${{ secrets.HEROKU_APP_NAME }}"
        appdir: backend/app 
